%%Cauclation for DMI 2024_3_25
%%The i+1 in this code correlated to i-1 in the reality system
%%This is actucally the mix of J3 and J4 in exchange.m
%% next means the layer in positive z direction(i-1 in the code)
%% pre means the layer in negative z direction(i+1 in the code)
%% xuezhong modified the calcultation of DMI 
for i=1:natomH
    switch mod(i-1,3)
        case 0 %%tpye layer 1
            % pre means i+1 layer
            % nex means i-1 layer
            if i==1%layer 1 do not have the i-1 layer interaction
                mmxtmpd_nex(:,:,i)=0;
                mmytmpd_nex(:,:,i)=0;
                mmztmpd_nex(:,:,i)=0;
            else
                mmxtmpd_nex(:,:,i)=(atomtype_layer1or.*(mmx_0n1(:,:,i-1) ...
                    +mmx_n1p1(:,:,i-1)+mmx_p1p1(:,:,i-1)-mmx_0p2(:,:,i-1)-...
                    mmx_n10(:,:,i-1)-mmx_p10(:,:,i-1))+atomtype_layer1gr.*...
                    (mmx_0p1(:,:,i-1)+mmx_n1n1(:,:,i-1)+mmx_p1n1(:,:,i-1)-mmx(:,:,i-1)));

                mmytmpd_nex(:,:,i)=(atomtype_layer1or.*(mmy_0n1(:,:,i-1)+ ...
                    mmy_n1p1(:,:,i-1)+mmy_p1p1(:,:,i-1)-mmy_0p2(:,:,i-1)-...
                    mmy_n10(:,:,i-1)-mmy_p10(:,:,i-1))+atomtype_layer1gr.* ...
                    (mmy_0p1(:,:,i-1)+mmy_n1n1(:,:,i-1)+mmy_p1n1(:,:,i-1)-mmy(:,:,i-1)));

                mmztmpd_nex(:,:,i)=(atomtype_layer1or.*(mmz_0n1(:,:,i-1)+ ...
                    mmz_n1p1(:,:,i-1)+mmz_p1p1(:,:,i-1)-mmz_0p2(:,:,i-1)-...
                    mmz_n10(:,:,i-1)-mmz_p10(:,:,i-1))+atomtype_layer1gr.* ...
                    (mmz_0p1(:,:,i-1)+mmz_n1n1(:,:,i-1)+mmz_p1n1(:,:,i-1)-mmz(:,:,i-1)));
            end
            mmxtmpd_pre(:,:,i)=atomtype_layer1gr.*(-mmx_0p1(:,:,i+1)-...
                mmx_n1n1(:,:,i+1)-mmx_p1n1(:,:,i+1)+mmx_0n2(:,:,i+1)+...
                mmx_p10(:,:,i+1)+mmx_n10(:,:,i+1))-atomtype_layer1or.*...
                (mmx_0n1(:,:,i+1)+mmx_p1p1(:,:,i+1)+mmx_n1p1(:,:,i+1)-mmx(:,:,i+1));

            mmytmpd_pre(:,:,i)=atomtype_layer1gr.*(-mmy_0p1(:,:,i+1)-...
                mmy_n1n1(:,:,i+1)-mmy_p1n1(:,:,i+1)+mmy_0n2(:,:,i+1)+...
                mmy_p10(:,:,i+1)+mmy_n10(:,:,i+1))-atomtype_layer1or.* ...
                (mmy_0n1(:,:,i+1)+mmy_p1p1(:,:,i+1)+mmy_n1p1(:,:,i+1)-mmy(:,:,i+1));

            mmztmpd_pre(:,:,i)=atomtype_layer1gr.*(-mmz_0p1(:,:,i+1)-...
                mmz_n1n1(:,:,i+1)-mmz_p1n1(:,:,i+1)+mmz_0n2(:,:,i+1)+...
                mmz_p10(:,:,i+1)+mmz_n10(:,:,i+1))-atomtype_layer1or.* ...
                (mmz_0n1(:,:,i+1)+mmz_p1p1(:,:,i+1)+mmz_n1p1(:,:,i+1)-mmz(:,:,i+1));


        case 1
            mmxtmpd_pre(:,:,i)=atomtype_layer2blue.*(-mmx_0p2(:,:,i+1)-...
                mmx_n10(:,:,i+1)-mmx_p10(:,:,i+1)+...
                mmx_0n1(:,:,i+1)+mmx_n1p1(:,:,i+1)+...
                mmx_p1p1(:,:,i+1))-...
                atomtype_layer2p.*(mmx_0n1(:,:,i+1)+...
                mmx_n1p1(:,:,i+1)+mmx_p1p1(:,:,i+1)-mmx(:,:,i+1));
            mmytmpd_pre(:,:,i)=atomtype_layer2blue.*(-mmy_0p2(:,:,i+1)-...
                mmy_n10(:,:,i+1)-mmy_p10(:,:,i+1)+...
                mmy_0n1(:,:,i+1)+mmy_n1p1(:,:,i+1)+...
                mmy_p1p1(:,:,i+1))-...
                atomtype_layer2p.*(mmy_0n1(:,:,i+1)+...
                mmy_n1p1(:,:,i+1)+mmy_p1p1(:,:,i+1)-mmy(:,:,i+1));
            mmztmpd_pre(:,:,i)=atomtype_layer2blue.*(-mmz_0p2(:,:,i+1)-...
                mmz_n10(:,:,i+1)-mmz_p10(:,:,i+1)+...
                mmz_0n1(:,:,i+1)+mmz_n1p1(:,:,i+1)+...
                mmz_p1p1(:,:,i+1))-...
                atomtype_layer2p.*(mmz_0n1(:,:,i+1)+...
                mmz_n1p1(:,:,i+1)+mmz_p1p1(:,:,i+1)-mmz(:,:,i+1));

            mmxtmpd_nex(:,:,i)=atomtype_layer2p.*(mmx_0n1(:,:,i-1)+...
                mmx_n1p1(:,:,i-1)+mmx_p1p1(:,:,i-1)-...
                mmx_0p1(:,:,i-1)-mmx_n1n1(:,:,i-1)-...
                mmx_p1n1(:,:,i-1))+...
                atomtype_layer2blue.*(mmx_0p2(:,:,i-1)+...
                mmx_n10(:,:,i-1)+mmx_p10(:,:,i-1)-mmx(:,:,i-1));
            mmytmpd_nex(:,:,i)=atomtype_layer2p.*(mmy_0n1(:,:,i-1)+...
                mmy_n1p1(:,:,i-1)+mmy_p1p1(:,:,i-1)-...
                mmy_0p1(:,:,i-1)-mmy_n1n1(:,:,i-1)-...
                mmy_p1n1(:,:,i-1))+...
                atomtype_layer2blue.*(mmy_0p2(:,:,i-1)+...
                mmy_n10(:,:,i-1)+mmy_p10(:,:,i-1)-mmy(:,:,i-1));
            mmztmpd_nex(:,:,i)=atomtype_layer2p.*(mmz_0n1(:,:,i-1)+...
                mmz_n1p1(:,:,i-1)+mmz_p1p1(:,:,i-1)-...
                mmz_0p1(:,:,i-1)-mmz_n1n1(:,:,i-1)-...
                mmz_p1n1(:,:,i-1))+...
                atomtype_layer2blue.*(mmz_0p2(:,:,i-1)+...
                mmz_n10(:,:,i-1)+mmz_p10(:,:,i-1)-mmz(:,:,i-1));
        case 2%layer end do not have the i+1 layer interaction
            if i==natomH
                mmxtmpd_pre(:,:,i)=0;
                mmytmpd_pre(:,:,i)=0;
                mmztmpd_pre(:,:,i)=0;
            else
                mmxtmpd_pre(:,:,i)=(-atomtype_layer3red.*(mmx_0n2(:,:,i+1)+...
                    mmx_n10(:,:,i+1)+mmx_p10(:,:,i+1)-mmx(:,:,i+1))+...
                    atomtype_layer3black.*(mmx_0n1(:,:,i+1)+...
                    mmx_n1p1(:,:,i+1)+mmx_p1p1(:,:,i+1)-...
                    mmx_0p1(:,:,i+1)-mmx_n1n1(:,:,i+1)-...
                    mmx_p1n1(:,:,i+1)));
                mmytmpd_pre(:,:,i)=(-atomtype_layer3red.*(mmy_0n2(:,:,i+1)+...
                    mmy_n10(:,:,i+1)+mmy_p10(:,:,i+1)-mmy(:,:,i+1))+...
                    atomtype_layer3black.*(mmy_0n1(:,:,i+1)+...
                    mmy_n1p1(:,:,i+1)+mmy_p1p1(:,:,i+1)-...
                    mmy_0p1(:,:,i+1)-mmy_n1n1(:,:,i+1)-...
                    mmy_p1n1(:,:,i+1)));
                mmztmpd_pre(:,:,i)=(-atomtype_layer3red.*(mmz_0n2(:,:,i+1)+...
                    mmz_n10(:,:,i+1)+mmz_p10(:,:,i+1)-mmz(:,:,i+1))+...
                    atomtype_layer3black.*(mmz_0n1(:,:,i+1)+...
                    mmz_n1p1(:,:,i+1)+mmz_p1p1(:,:,i+1)-...
                    mmz_0p1(:,:,i+1)-mmz_n1n1(:,:,i+1)-...
                    mmz_p1n1(:,:,i+1)));
            end
            mmxtmpd_nex(:,:,i)=atomtype_layer3red.*(mmx_0n2(:,:,i-1)+...
                mmx_n10(:,:,i-1)+mmx_p10(:,:,i-1)-...
                mmx_0p1(:,:,i-1)-mmx_n1n1(:,:,i-1)-...
                mmx_p1n1(:,:,i-1))+...
                atomtype_layer3black.*(mmx_0p1(:,:,i-1)+...
                mmx_n1n1(:,:,i-1)+mmx_p1n1(:,:,i-1)-mmx(:,:,i-1));
            mmytmpd_nex(:,:,i)=atomtype_layer3red.*(mmy_0n2(:,:,i-1)+...
                mmy_n10(:,:,i-1)+mmy_p10(:,:,i-1)-...
                mmy_0p1(:,:,i-1)-mmy_n1n1(:,:,i-1)-...
                mmy_p1n1(:,:,i-1))+...
                atomtype_layer3black.*(mmy_0p1(:,:,i-1)+...
                mmy_n1n1(:,:,i-1)+mmy_p1n1(:,:,i-1)-mmy(:,:,i-1));
            mmztmpd_nex(:,:,i)=atomtype_layer3red.*(mmz_0n2(:,:,i-1)+...
                mmz_n10(:,:,i-1)+mmz_p10(:,:,i-1)-...
                mmz_0p1(:,:,i-1)-mmz_n1n1(:,:,i-1)-...
                mmz_p1n1(:,:,i-1))+...
                atomtype_layer3black.*(mmz_0p1(:,:,i-1)+...
                mmz_n1n1(:,:,i-1)+mmz_p1n1(:,:,i-1)-mmz(:,:,i-1));

        otherwise
            error('unexpected index');
    end
end

