%%Cauclation for DMI 2024_3_25
%%The i+1 in this code correlated to i-1 in the reality system
%%This is actucally the mix of J3 and J4 in exchange.m
%% next means the layer in positive z direction(i-1 in the code)
%% pre means the layer in negative z direction(i+1 in the code)
for i=1:h     
     if i==1 || i==h
        r=0;
     else 
        r=1;
     end   
     
    switch mod(i-1,3)
        case 0 %%tpye layer 1
%%  pre means i+1 layer
               if i==1
                   bb=i+1;
               else 
                   bb=i;
               end
       mmxtmpd_pre(:,:,i)=atomtype_layer1gr.*mmx_0p1(:,:,i+1)+...
                          atomtype_layer1gr.*mmx_n1n1(:,:,i+1)+...
                          atomtype_layer1gr.*mmx_p1n1(:,:,i+1)+...
                          atomtype_layer1gr.*mmx_0n2(:,:,i+1)+...
                          atomtype_layer1gr.*mmx_p10(:,:,i+1)+...
                          atomtype_layer1gr.*mmx_n10(:,:,i+1);
       mmytmpd_pre(:,:,i)=atomtype_layer1gr.*mmy_0p1(:,:,i+1)+...
                          atomtype_layer1gr.*mmy_n1n1(:,:,i+1)+...
                          atomtype_layer1gr.*mmy_p1n1(:,:,i+1)+...
                          atomtype_layer1gr.*mmy_0n2(:,:,i+1)+...
                          atomtype_layer1gr.*mmy_p10(:,:,i+1)+...
                          atomtype_layer1gr.*mmy_n10(:,:,i+1);
       mmztmpd_pre(:,:,i)=atomtype_layer1gr.*mmz_0p1(:,:,i+1)+...
                          atomtype_layer1gr.*mmz_n1n1(:,:,i+1)+...
                          atomtype_layer1gr.*mmz_p1n1(:,:,i+1)+...
                          atomtype_layer1gr.*mmz_0n2(:,:,i+1)+...
                          atomtype_layer1gr.*mmz_p10(:,:,i+1)+...
                          atomtype_layer1gr.*mmz_n10(:,:,i+1);
       mmxtmpd_nex(:,:,i)=r*(atomtype_layer1or.*mmx_0n1(:,:,bb-1)+ ...
                          atomtype_layer1or.*mmx_n1p1(:,:,bb-1)+...
                          atomtype_layer1or.*mmx_p1p1(:,:,bb-1)+...
                          atomtype_layer1gr.*mmx_0p1(:,:,bb-1)+...
                          atomtype_layer1gr.*mmx_n1n1(:,:,bb-1)+...
                          atomtype_layer1gr.*mmx_p1n1(:,:,bb-1));
       mmytmpd_nex(:,:,i)=r*(atomtype_layer1or.*mmy_0n1(:,:,bb-1)+ ...
                          atomtype_layer1or.*mmy_n1p1(:,:,bb-1)+...
                          atomtype_layer1or.*mmx_p1p1(:,:,bb-1)+...
                          atomtype_layer1gr.*mmy_0p1(:,:,bb-1)+...
                          atomtype_layer1gr.*mmy_n1n1(:,:,bb-1)+...
                          atomtype_layer1gr.*mmy_p1n1(:,:,bb-1));
      mmztmpd_nex(:,:,i)=r*(atomtype_layer1or.*mmz_0n1(:,:,bb-1)+ ...
                          atomtype_layer1or.*mmz_n1p1(:,:,bb-1)+...
                          atomtype_layer1or.*mmz_p1p1(:,:,bb-1)+...
                          atomtype_layer1gr.*mmz_0p1(:,:,bb-1)+...
                          atomtype_layer1gr.*mmz_n1n1(:,:,bb-1)+...
                          atomtype_layer1gr.*mmz_p1n1(:,:,bb-1));
    case 1
       mmxtmpd_pre(:,:,i)=atomtype_layer2blue.*mmx_0p2(:,:,i+1)+...
                          atomtype_layer2blue.*mmx_n10(:,:,i+1)+...
                          atomtype_layer2blue.*mmx_p10(:,:,i+1)+...
                          atomtype_layer2blue.*mmx_0n1(:,:,i+1)+...
                          atomtype_layer2blue.*mmx_n1p1(:,:,i+1)+...
                          atomtype_layer2blue.*mmx_p1p1(:,:,i+1);
       mmytmpd_pre(:,:,i)=atomtype_layer2blue.*mmy_0p2(:,:,i+1)+...
                          atomtype_layer2blue.*mmy_n10(:,:,i+1)+...
                          atomtype_layer2blue.*mmy_p10(:,:,i+1)+...
                          atomtype_layer2blue.*mmy_0n1(:,:,i+1)+...
                          atomtype_layer2blue.*mmy_n1p1(:,:,i+1)+...
                          atomtype_layer2blue.*mmy_p1p1(:,:,i+1);     
       mmztmpd_pre(:,:,i)=atomtype_layer2blue.*mmz_0p2(:,:,i+1)+...
                          atomtype_layer2blue.*mmz_n10(:,:,i+1)+...
                          atomtype_layer2blue.*mmz_p10(:,:,i+1)+...
                          atomtype_layer2blue.*mmz_0n1(:,:,i+1)+...
                          atomtype_layer2blue.*mmz_n1p1(:,:,i+1)+...
                          atomtype_layer2blue.*mmz_p1p1(:,:,i+1);

       mmxtmpd_nex(:,:,i)=atomtype_layer2p.*mmx_0n1(:,:,i-1)+...
                          atomtype_layer2p.*mmx_n1p1(:,:,i-1)+...
                          atomtype_layer2p.*mmx_p1p1(:,:,i-1)+...
                          atomtype_layer2blue.*mmx_0p2(:,:,i-1)+...
                          atomtype_layer2blue.*mmx_n10(:,:,i-1)+...
                          atomtype_layer2blue.*mmx_p10(:,:,i-1);
       mmytmpd_nex(:,:,i)=atomtype_layer2p.*mmy_0n1(:,:,i-1)+...
                          atomtype_layer2p.*mmy_n1p1(:,:,i-1)+...
                          atomtype_layer2p.*mmy_p1p1(:,:,i-1)+...
                          atomtype_layer2blue.*mmy_0p2(:,:,i-1)+...
                          atomtype_layer2blue.*mmy_n10(:,:,i-1)+...
                          atomtype_layer2blue.*mmy_p10(:,:,i-1); 
       mmztmpd_nex(:,:,i)=atomtype_layer2p.*mmz_0n1(:,:,i-1)+...
                          atomtype_layer2p.*mmz_n1p1(:,:,i-1)+...
                          atomtype_layer2p.*mmz_p1p1(:,:,i-1)+...
                          atomtype_layer2blue.*mmz_0p2(:,:,i-1)+...
                          atomtype_layer2blue.*mmz_n10(:,:,i-1)+...
                          atomtype_layer2blue.*mmz_p10(:,:,i-1);
         case 2
               if i==h
                   hh=i-1;
               else 
                   hh=i;
               end
       mmxtmpd_pre(:,:,i)=r*(atomtype_layer3red.*mmx_0p1(:,:,hh+1)+...
                          atomtype_layer3red.*mmx_n1n1(:,:,hh+1)+...
                          atomtype_layer3red.*mmx_p1n1(:,:,hh+1)+...
                          atomtype_layer3black.*mmx_0n1(:,:,hh+1)+...
                          atomtype_layer3black.*mmx_n1p1(:,:,hh+1)+...
                          atomtype_layer3black.*mmx_p1p1(:,:,hh+1));
       mmytmpd_pre(:,:,i)=r*(atomtype_layer3red.*mmy_0p1(:,:,hh+1)+...
                          atomtype_layer3red.*mmy_n1n1(:,:,hh+1)+...
                          atomtype_layer3red.*mmy_p1n1(:,:,hh+1)+...
                          atomtype_layer3black.*mmy_0n1(:,:,hh+1)+...
                          atomtype_layer3black.*mmy_n1p1(:,:,hh+1)+...
                          atomtype_layer3black.*mmy_p1p1(:,:,hh+1));       
       mmztmpd_pre(:,:,i)=r*(atomtype_layer3red.*mmz_0p1(:,:,hh+1)+...
                          atomtype_layer3red.*mmz_n1n1(:,:,hh+1)+...
                          atomtype_layer3red.*mmz_p1n1(:,:,hh+1)+...
                          atomtype_layer3black.*mmz_0n1(:,:,hh+1)+...
                          atomtype_layer3black.*mmz_n1p1(:,:,hh+1)+...
                          atomtype_layer3black.*mmz_p1p1(:,:,hh+1));
       mmxtmpd_nex(:,:,i)=atomtype_layer3red.*mmx_0n2(:,:,i-1)+...
                          atomtype_layer3red.*mmx_n10(:,:,i-1)+...
                          atomtype_layer3red.*mmx_p10(:,:,i-1)+...
                          atomtype_layer3black.*mmx_0p1(:,:,i-1)+...
                          atomtype_layer3black.*mmx_n1n1(:,:,i-1)+...
                          atomtype_layer3black.*mmx_p1n1(:,:,i-1);
       mmytmpd_nex(:,:,i)=atomtype_layer3red.*mmy_0n2(:,:,i-1)+...
                          atomtype_layer3red.*mmy_n10(:,:,i-1)+...
                          atomtype_layer3red.*mmy_p10(:,:,i-1)+...
                          atomtype_layer3black.*mmy_0p1(:,:,i-1)+...
                          atomtype_layer3black.*mmy_n1n1(:,:,i-1)+...
                          atomtype_layer3black.*mmy_p1n1(:,:,i-1);
       mmztmpd_nex(:,:,i)=atomtype_layer3red.*mmz_0n2(:,:,i-1)+...
                          atomtype_layer3red.*mmz_n10(:,:,i-1)+...
                          atomtype_layer3red.*mmz_p10(:,:,i-1)+...
                          atomtype_layer3black.*mmz_0p1(:,:,i-1)+...
                          atomtype_layer3black.*mmz_n1n1(:,:,i-1)+...
                          atomtype_layer3black.*mmz_p1n1(:,:,i-1);
      
        otherwise
            error('unexpected index');
    end
   
        mmxtmpdmi_pre(:,:,i)=mmxtmpd_pre(:,:,i);mmytmpdmi_pre(:,:,i)=mmytmpd_pre(:,:,i);mmztmpdmi_pre(:,:,i)=mmztmpd_pre(:,:,i);
        mmxtmpdmi_nex(:,:,i)=mmxtmpd_nex(:,:,i);mmytmpdmi_nex(:,:,i)=mmytmpd_nex(:,:,i);mmztmpdmi_nex(:,:,i)=mmztmpd_nex(:,:,i);
end

