%% zf modify

for i=1:h 
     if i==1 || i==h
        b=0;
     else 
        b=1;
     end    
        %blue in the 2nd layer is identical to orange in 1st layer
        %green in the 1st layer is identical to red in 3rd(last) layer
        %red in the 3nd layer is identical to green in 1st layer

        %purple in the 2nd layer is identical to black in 3rd(last) layer
        %black in the 3nd layer is identical to purple in 2nd layer
        switch mod(i-1,3)
            case 0
                %% calculate J1
               
                mmxtmpJ1(:,:,i)=b*(atomtype_layer3red.*mmx_zp1_nex(:,:,i))+atomtype_layer2blue.*mmx_zn1_pre(:,:,i);
                mmytmpJ1(:,:,i)=b*(atomtype_layer3red.*mmy_zp1_nex(:,:,i))+atomtype_layer2blue.*mmy_zn1_pre(:,:,i);
                mmztmpJ1(:,:,i)=b*(atomtype_layer3red.*mmz_zp1_nex(:,:,i))+atomtype_layer2blue.*mmz_zn1_pre(:,:,i);
                %% calculate J2
                %J2 experienced by green atoms

                shift_matx_gr=mmx_0n2_gr(:,:,i)+mmx_p10_gr(:,:,i)...
                    +mmx_n10_gr(:,:,i);
                shift_maty_gr=mmy_0n2_gr(:,:,i)+mmy_p10_gr(:,:,i)...
                    +mmy_n10_gr(:,:,i);
                shift_matz_gr=mmz_0n2_gr(:,:,i)+mmz_p10_gr(:,:,i)...
                    +mmz_n10_gr(:,:,i);
                %J2 experienced by orange atoms
                shift_matx_or=mmx_0p2_or(:,:,i)+mmx_p10_or(:,:,i)+...
                    mmx_n10_or(:,:,i);
                shift_maty_or=mmy_0p2_or(:,:,i)+mmy_p10_or(:,:,i)+...
                    mmy_n10_or(:,:,i);
                shift_matz_or=mmz_0p2_or(:,:,i)+mmz_p10_or(:,:,i)+...
                    mmz_n10_or(:,:,i);

                mmxtmpJ2(:,:,i)=shift_matx_gr+shift_matx_or;
                mmytmpJ2(:,:,i)=shift_maty_gr+shift_maty_or;
                mmztmpJ2(:,:,i)=shift_matz_gr+shift_matz_or;

                %% calculate J3
                %J3 experienced by green atoms
                shift_matx_gr=atomtype_layer1gr.*mmx_0p1_pre(:,:,i)+atomtype_layer1gr.*mmx_n1n1_pre(:,:,i)+...
                    atomtype_layer1gr.*mmx_p1n1_pre(:,:,i);
                shift_maty_gr=atomtype_layer1gr.*mmy_0p1_pre(:,:,i)+atomtype_layer1gr.*mmy_n1n1_pre(:,:,i)+...
                    atomtype_layer1gr.*mmy_p1n1_pre(:,:,i);
                shift_matz_gr=atomtype_layer1gr.*mmz_0p1_pre(:,:,i)+atomtype_layer1gr.*mmz_n1n1_pre(:,:,i)+...
                    atomtype_layer1gr.*mmz_p1n1_pre(:,:,i);
                %J3 experienced by orange atoms
                %black in the 3nd layer is identical to purple in 2nd layer
                shift_matx_or=b*(atomtype_layer1or.*mmx_0n1_nex(:,:,i)+atomtype_layer1or.*mmx_n1p1_nex(:,:,i)+...
                    atomtype_layer1or.*mmx_p1p1_nex(:,:,i));
                shift_maty_or=b*(atomtype_layer1or.*mmy_0n1_nex(:,:,i)+atomtype_layer1or.*mmy_n1p1_nex(:,:,i)+...
                    atomtype_layer1or.*mmy_p1p1_nex(:,:,i));
                shift_matz_or=b*(atomtype_layer1or.*mmz_0n1_nex(:,:,i)+atomtype_layer1or.*mmz_n1p1_nex(:,:,i)+...
                    atomtype_layer1or.*mmz_p1p1_nex(:,:,i));

                mmxtmpJ3(:,:,i)=shift_matx_gr+shift_matx_or;
                mmytmpJ3(:,:,i)=shift_maty_gr+shift_maty_or;
                mmztmpJ3(:,:,i)=shift_matz_gr+shift_matz_or;

                %% calculate J4
                %J4 experienced by green atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                %black in the 3nd layer is identical to purple in 2nd layer
                shift_matx_gr=atomtype_layer1gr.*mmx_0n2_pre(:,:,i)+...
                    atomtype_layer1gr.*mmx_p10_pre(:,:,i)+...
                    atomtype_layer1gr.*mmx_n10_pre(:,:,i)+...
                    b*(atomtype_layer1gr.*mmx_0p1_nex(:,:,i)+...
                    atomtype_layer1gr.*mmx_n1n1_nex(:,:,i)+...
                    atomtype_layer1gr.*mmx_p1n1_nex(:,:,i));
                shift_maty_gr=atomtype_layer1gr.*mmy_0n2_pre(:,:,i)+...
                    atomtype_layer1gr.*mmy_p10_pre(:,:,i)+...
                    atomtype_layer1gr.*mmy_n10_pre(:,:,i)+...
                    b*(atomtype_layer1gr.*mmy_0p1_nex(:,:,i)+...
                    atomtype_layer1gr.*mmy_n1n1_nex(:,:,i)+...
                    atomtype_layer1gr.*mmy_p1n1_nex(:,:,i));
                shift_matz_gr=atomtype_layer1gr.*mmz_0n2_pre(:,:,i)+...
                    atomtype_layer1gr.*mmz_p10_pre(:,:,i)+...
                    atomtype_layer1gr.*mmz_n10_pre(:,:,i)+...
                    b*(atomtype_layer1gr.*mmz_0p1_nex(:,:,i)+...
                    atomtype_layer1gr.*mmz_n1n1_nex(:,:,i)+...
                    atomtype_layer1gr.*mmz_p1n1_nex(:,:,i));
                %J4 experienced by orange atoms
                %red in the 3nd layer is identical to green in 1st layer
                shift_matx_or=atomtype_layer1or.*mmx_0n1_pre(:,:,i)+...
                    atomtype_layer1or.*mmx_n1p1_pre(:,:,i)+...
                    atomtype_layer1or.*mmx_p1p1_pre(:,:,i)+...
                    b*(atomtype_layer1or.*mmx_0p2_nex(:,:,i)+...
                    atomtype_layer1or.*mmx_n10_nex(:,:,i)+...
                    atomtype_layer1or.*mmx_p10_nex(:,:,i));
                shift_maty_or=atomtype_layer1or.*mmy_0n1_pre(:,:,i)+...
                    atomtype_layer1or.*mmy_n1p1_pre(:,:,i)+...
                    atomtype_layer1or.*mmy_p1p1_pre(:,:,i)+...
                    b*(atomtype_layer1or.*mmy_0p2_nex(:,:,i)+...
                    atomtype_layer1or.*mmy_n10_nex(:,:,i)+...
                    atomtype_layer1or.*mmy_p10_nex(:,:,i));
                shift_matz_or=atomtype_layer1or.*mmz_0n1_pre(:,:,i)+...
                    atomtype_layer1or.*mmz_n1p1_pre(:,:,i)+...
                    atomtype_layer1or.*mmz_p1p1_pre(:,:,i)+...
                    b*(atomtype_layer1or.*mmz_0p2_nex(:,:,i)+...
                    atomtype_layer1or.*mmz_n10_nex(:,:,i)+...
                    atomtype_layer1or.*mmz_p10_nex(:,:,i));

                mmxtmpJ4(:,:,i)=shift_matx_gr+shift_matx_or;
                mmytmpJ4(:,:,i)=shift_maty_gr+shift_maty_or;
                mmztmpJ4(:,:,i)=shift_matz_gr+shift_matz_or;

            case 1
                %% calculate J1
                mmxtmpJ1(:,:,i)=atomtype_layer3black.*mmx_zn1_pre(:,:,i)+atomtype_layer2blue.*mmx_zp1_nex(:,:,i);
                mmytmpJ1(:,:,i)=atomtype_layer3black.*mmy_zn1_pre(:,:,i)+atomtype_layer2blue.*mmy_zp1_nex(:,:,i);
                mmztmpJ1(:,:,i)=atomtype_layer3black.*mmz_zn1_pre(:,:,i)+atomtype_layer2blue.*mmz_zp1_nex(:,:,i);

                %% calculate J2
                %J2 experienced by blue atoms
                shift_matx_blue=mmx_0n1_blu(:,:,i)+mmx_n1p1_blu(:,:,i)+...
                    mmx_p1p1_blu(:,:,i);
                shift_maty_blue=mmy_0n1_blu(:,:,i)+mmy_n1p1_blu(:,:,i)+...
                    mmy_p1p1_blu(:,:,i);
                shift_matz_blue=mmz_0n1_blu(:,:,i)+mmz_n1p1_blu(:,:,i)+...
                    mmz_p1p1_blu(:,:,i);

                %J2 experienced by purple atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                shift_matx_purple=mmx_0p1_pu(:,:,i)+mmx_n1n1_pu(:,:,i)+...
                     mmx_p1n1_pu(:,:,i);
                shift_maty_purple=mmy_0p1_pu(:,:,i)+mmy_n1n1_pu(:,:,i)+...
                     mmy_p1n1_pu(:,:,i);
                shift_matz_purple=mmz_0p1_pu(:,:,i)+mmz_n1n1_pu(:,:,i)+...
                     mmz_p1n1_pu(:,:,i);

                mmxtmpJ2(:,:,i)=shift_matx_blue+shift_matx_purple;
                mmytmpJ2(:,:,i)=shift_maty_blue+shift_maty_purple;
                mmztmpJ2(:,:,i)=shift_matz_blue+shift_matz_purple;

                %% calculate J3
                %J3 experienced by blue atoms
                %red in the 3rd layer is identical to green in 1st layer
                shift_matx_blue=atomtype_layer2blue.*mmx_0p2_pre(:,:,i)+atomtype_layer2blue.*mmx_n10_pre(:,:,i)+...
                    atomtype_layer2blue.*mmx_p10_pre(:,:,i);
                shift_maty_blue=atomtype_layer2blue.*mmy_0p2_pre(:,:,i)+atomtype_layer2blue.*mmy_n10_pre(:,:,i)+...
                    atomtype_layer2blue.*mmy_p10_pre(:,:,i);
                shift_matz_blue=atomtype_layer2blue.*mmz_0p2_pre(:,:,i)+atomtype_layer2blue.*mmz_n10_pre(:,:,i)+...
                    atomtype_layer2blue.*mmz_p10_pre(:,:,i);
                %J3 experienced by purple atoms
                shift_matx_purple=atomtype_layer2p.*mmx_0n1_nex(:,:,i)+atomtype_layer2p.*mmx_n1p1_nex(:,:,i)+...
                    atomtype_layer2p.*mmx_p1p1_nex(:,:,i);
                shift_maty_purple=atomtype_layer2p.*mmy_0n1_nex(:,:,i)+atomtype_layer2p.*mmy_n1p1_nex(:,:,i)+...
                    atomtype_layer2p.*mmy_p1p1_nex(:,:,i);
                shift_matz_purple=atomtype_layer2p.*mmz_0n1_nex(:,:,i)+atomtype_layer2p.*mmz_n1p1_nex(:,:,i)+...
                    atomtype_layer2p.*mmz_p1p1_nex(:,:,i);

                mmxtmpJ3(:,:,i)=shift_matx_blue+shift_matx_purple;
                mmytmpJ3(:,:,i)=shift_maty_blue+shift_maty_purple;
                mmztmpJ3(:,:,i)=shift_matz_blue+shift_matz_purple;

                %% calculate J4
                %J4 experienced by blue atoms
                %black in the 3nd layer is identical to purple in 2nd layer
                shift_matx_blue=atomtype_layer2blue.*mmx_0n1_pre(:,:,i)+...
                atomtype_layer2blue.*mmx_n1p1_pre(:,:,i)+...
                atomtype_layer2blue.*mmx_p1p1_pre(:,:,i)+...
                atomtype_layer2blue.*mmx_0p2_nex(:,:,i)+...
                atomtype_layer2blue.*mmx_n10_nex(:,:,i)+...
                atomtype_layer2blue.*mmx_p10_nex(:,:,i);
                shift_maty_black=atomtype_layer2blue.*mmy_0n1_pre(:,:,i)+...
                atomtype_layer2blue.*mmy_n1p1_pre(:,:,i)+...
                atomtype_layer2blue.*mmy_p1p1_pre(:,:,i)+...
                atomtype_layer2blue.*mmy_0p2_nex(:,:,i)+...
                atomtype_layer2blue.*mmy_n10_nex(:,:,i)+...
                atomtype_layer2blue.*mmy_p10_nex(:,:,i);
                shift_matz_black=atomtype_layer2blue.*mmz_0n1_pre(:,:,i)+...
                atomtype_layer2blue.*mmz_n1p1_pre(:,:,i)+...
                atomtype_layer2blue.*mmz_p1p1_pre(:,:,i)+...
                atomtype_layer2blue.*mmz_0p2_nex(:,:,i)+...
                atomtype_layer2blue.*mmz_n10_nex(:,:,i)+...
                atomtype_layer2blue.*mmz_p10_nex(:,:,i);
                %J4 experienced by purple atoms
                %red in the 3nd layer is identical to green in 1st layer
                shift_matx_purple=atomtype_layer2p.*mmx_0n1_pre(:,:,i)+...
                atomtype_layer2p.*mmx_n1p1_pre(:,:,i)+...
                atomtype_layer2p.*mmx_p1p1_pre(:,:,i)+...
                atomtype_layer2p.*mmx_0p1_nex(:,:,i)+...
                atomtype_layer2p.*mmx_n1n1_nex(:,:,i)+...
                atomtype_layer2p.*mmx_p1n1_nex(:,:,i);
                shift_maty_purple=atomtype_layer2p.*mmy_0n1_pre(:,:,i)+...
                atomtype_layer2p.*mmy_n1p1_pre(:,:,i)+...
                atomtype_layer2p.*mmy_p1p1_pre(:,:,i)+...
                atomtype_layer2p.*mmy_0p1_nex(:,:,i)+...
                atomtype_layer2p.*mmy_n1n1_nex(:,:,i)+...
                atomtype_layer2p.*mmy_p1n1_nex(:,:,i);
                shift_matz_purple=atomtype_layer2p.*mmz_0n1_pre(:,:,i)+...
                atomtype_layer2p.*mmz_n1p1_pre(:,:,i)+...
                atomtype_layer2p.*mmz_p1p1_pre(:,:,i)+...
                atomtype_layer2p.*mmz_0p1_nex(:,:,i)+...
                atomtype_layer2p.*mmz_n1n1_nex(:,:,i)+...
                atomtype_layer2p.*mmz_p1n1_nex(:,:,i);

                mmxtmpJ4(:,:,i)=shift_matx_blue+shift_matx_purple;
                mmytmpJ4(:,:,i)=shift_maty_black+shift_maty_purple;
                mmztmpJ4(:,:,i)=shift_matz_black+shift_matz_purple;

            case 2
                %% calculate J1
                mmxtmpJ1(:,:,i)=b*(atomtype_layer1gr.*mmx_zn1_pre(:,:,i))+atomtype_layer2p.*mmx_zp1_nex(:,:,i);  
                mmytmpJ1(:,:,i)=b*(atomtype_layer1gr.*mmy_zn1_pre(:,:,i))+atomtype_layer2p.*mmy_zp1_nex(:,:,i);  
                mmztmpJ1(:,:,i)=b*(atomtype_layer1gr.*mmz_zn1_pre(:,:,i))+atomtype_layer2p.*mmz_zp1_nex(:,:,i);  

                %% calculate J2
                %J2 experienced by black atoms
                %green in the 1st layer is identical to red in 3rd(last) layer
                shift_matx_black=mmx_0n1_bla(:,:,i)+mmx_n1p1_bla(:,:,i)+...
                    mmx_p1p1_bla(:,:,i);
                shift_maty_black=mmy_0n1_bla(:,:,i)+mmy_n1p1_bla(:,:,i)+...
                    mmy_p1p1_bla(:,:,i);
                shift_matz_black=mmz_0n1_bla(:,:,i)+mmz_n1p1_bla(:,:,i)+...
                    mmz_p1p1_bla(:,:,i);
                %J2 experienced by red atoms
                %purple in the 2nd layer is identical to black in 3rd(last) layer
                shift_matx_red=mmx_0p1_red(:,:,i)+mmx_n1n1_red(:,:,i)+...
                    mmx_p1n1_red(:,:,i);
                shift_maty_red=mmy_0p1_red(:,:,i)+mmy_n1n1_red(:,:,i)+...
                    mmy_p1n1_red(:,:,i);
                shift_matz_red=mmz_0p1_red(:,:,i)+mmz_n1n1_red(:,:,i)+...
                    mmz_p1n1_red(:,:,i);
                mmxtmpJ2(:,:,i)=shift_matx_black+shift_matx_red;
                mmytmpJ2(:,:,i)=shift_maty_black+shift_maty_red;
                mmztmpJ2(:,:,i)=shift_matz_black+shift_matz_red;

                %% calculate J3
                %J3 for red atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                shift_matx_red=atomtype_layer3red.*mmx_0n2_nex(:,:,i)+atomtype_layer3red.*mmx_n10_nex(:,:,i)+...
                    atomtype_layer3red.*mmx_p10_nex(:,:,i);
                shift_maty_red=atomtype_layer3red.*mmy_0n2_nex(:,:,i)+atomtype_layer3red.*mmy_n10_nex(:,:,i)+...
                    atomtype_layer3red.*mmy_p10_nex(:,:,i);
                shift_matz_red=atomtype_layer3red.*mmz_0n2_nex(:,:,i)+atomtype_layer3red.*mmz_n10_nex(:,:,i)+...
                    atomtype_layer3red.*mmz_p10_nex(:,:,i);
                %J3 for black atoms
                shift_matx_black=atomtype_layer3red.*mmx_0p1_pre(:,:,i)+atomtype_layer3red.*mmx_n1n1_pre(:,:,i)+...
                    atomtype_layer3red.*mmx_p1n1_pre(:,:,i);
                shift_maty_black=atomtype_layer3red.*mmy_0p1_pre(:,:,i)+atomtype_layer3red.*mmy_n1n1_pre(:,:,i)+...
                    atomtype_layer3red.*mmy_p1n1_pre(:,:,i);
                shift_matz_black=atomtype_layer3red.*mmz_0p1_pre(:,:,i)+atomtype_layer3red.*mmz_n1n1_pre(:,:,i)+...
                    atomtype_layer3red.*mmy_p1n1_pre(:,:,i);

                mmxtmpJ3(:,:,i)=shift_matx_red+b*shift_matx_black;
                mmytmpJ3(:,:,i)=shift_maty_red+b*shift_maty_black;
                mmztmpJ3(:,:,i)=shift_matz_red+b*shift_matz_black;

                %% calculate J4
                %J4 experienced by black atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                shift_matx_black=b*(atomtype_layer3black.*mmx_0n1_pre(:,:,i)+...
                    atomtype_layer3black.*mmx_n1p1_pre(:,:,i)+...
                    atomtype_layer3black.*mmx_p1p1_pre(:,:,i))+...
                    atomtype_layer3black.*mmx_0p1_nex(:,:,i)+...
                    atomtype_layer3black.*mmx_n1n1_nex(:,:,i)+...
                    atomtype_layer3black.*mmx_p1n1_nex(:,:,i);
                shift_maty_black=b*(atomtype_layer3black.*mmy_0n1_pre(:,:,i)+...
                    atomtype_layer3black.*mmy_n1p1_pre(:,:,i)+...
                    atomtype_layer3black.*mmy_p1p1_pre(:,:,i))+...
                    atomtype_layer3black.*mmy_0p1_nex(:,:,i)+...
                    atomtype_layer3black.*mmy_n1n1_nex(:,:,i)+...
                    atomtype_layer3black.*mmy_p1n1_nex(:,:,i);
                shift_matz_black=b*(atomtype_layer3black.*mmz_0n1_pre(:,:,i)+...
                    atomtype_layer3black.*mmz_n1p1_pre(:,:,i)+...
                    atomtype_layer3black.*mmz_p1p1_pre(:,:,i))+...
                    atomtype_layer3black.*mmz_0p1_nex(:,:,i)+...
                    atomtype_layer3black.*mmz_n1n1_nex(:,:,i)+...
                    atomtype_layer3black.*mmz_p1n1_nex(:,:,i);
                %J4 experienced by red atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                shift_matx_red=b*(atomtype_layer3red.*mmx_p10_pre(:,:,i)+...
                    atomtype_layer3red.*mmx_n10_pre(:,:,i)+...
                    atomtype_layer3red.*mmx_0n2_pre(:,:,i))+...
                    atomtype_layer3red.*mmx_0p1_nex(:,:,i)+...
                    atomtype_layer3red.*mmx_n1n1_nex(:,:,i)+...
                    atomtype_layer3red.*mmx_p1n1_nex(:,:,i);
                shift_maty_red=b*(atomtype_layer3red.*mmy_p10_pre(:,:,i)+...
                    atomtype_layer3red.*mmy_n10_pre(:,:,i)+...
                    atomtype_layer3red.*mmy_0n2_pre(:,:,i))+...
                    atomtype_layer3red.*mmy_0p1_nex(:,:,i)+...
                    atomtype_layer3red.*mmy_n1n1_nex(:,:,i)+...
                    atomtype_layer3red.*mmy_p1n1_nex(:,:,i);
                shift_matz_red=b*(atomtype_layer3red.*mmz_p10_pre(:,:,i)+...
                    atomtype_layer3red.*mmz_n10_pre(:,:,i)+...
                    atomtype_layer3red.*mmz_0n2_pre(:,:,i))+...
                    atomtype_layer3red.*mmz_0p1_nex(:,:,i)+...
                    atomtype_layer3red.*mmz_n1n1_nex(:,:,i)+...
                    atomtype_layer3red.*mmz_p1n1_nex(:,:,i);

                mmxtmpJ4(:,:,i)=shift_matx_black+shift_matx_red;
                mmytmpJ4(:,:,i)=shift_maty_black+shift_maty_red;
                mmztmpJ4(:,:,i)=shift_matz_black+shift_matz_red;
            otherwise
                error('unexpected index');
        end
   
    mmxtmpJ_1(:,:,i)=mmxtmpJ1(:,:,i);mmytmpJ_1(:,:,i)=mmytmpJ1(:,:,i);mmztmpJ_1(:,:,i)=mmztmpJ1(:,:,i);mmxtmpJ_2(:,:,i)=mmxtmpJ2(:,:,i);mmytmpJ_2(:,:,i)=mmytmpJ2(:,:,i);mmztmpJ_2(:,:,i)=mmztmpJ2(:,:,i);
    mmxtmpJ_3(:,:,i)=mmxtmpJ3(:,:,i);mmytmpJ_3(:,:,i)=mmytmpJ3(:,:,i);mmztmpJ_3(:,:,i)=mmztmpJ3(:,:,i);mmxtmpJ_4(:,:,i)=mmxtmpJ4(:,:,i);mmytmpJ_4(:,:,i)=mmytmpJ4(:,:,i);mmztmpJ_4(:,:,i)=mmztmpJ4(:,:,i);
end
% load('debugtmp.mat');
%     isequal(mmxtmpJzx_1, mmxtmpJ_1)&isequal(mmytmpJzx_1, mmytmpJ_1)&isequal(mmztmpJzx_1, mmztmpJ_1)&...
%     isequal(mmxtmpJzx_2, mmxtmpJ_2)&isequal(mmytmpJzx_2, mmytmpJ_2)&isequal(mmztmpJzx_2, mmztmpJ_2)&...
%     isequal(mmxtmpJzx_3, mmxtmpJ_3)&isequal(mmytmpJzx_3, mmytmpJ_3)&isequal(mmztmpJzx_3, mmztmpJ_3)&...
%     isequal(mmxtmpJzx_4, mmxtmpJ_4)&isequal(mmytmpJzx_4, mmytmpJ_4)&isequal(mmztmpJzx_4, mmztmpJ_4)
