%% zf modify
for i=1:h
    if i==1
        %% calculate J1
        %J1 for orange atoms
        %no J1 for green atoms
        mmxtmpJ1(:,:,1)=atomtype_layer1or.*mmxtmp(:,:,2);
        mmytmpJ1(:,:,1)=atomtype_layer1or.*mmytmp(:,:,2);
        mmztmpJ1(:,:,1)=atomtype_layer1or.*mmztmp(:,:,2);

        %% calculate J2
        %J2 experienced by green atoms
        shift_matx_gr=circshift(atomtype_layer1or.*mmxtmp(:,:,1),[0,-2,0])+...
            circshift(atomtype_layer1or.*mmxtmp(:,:,1),[1,0,0])+...
            circshift(atomtype_layer1or.*mmxtmp(:,:,1),[-1,0,0]);
        shift_maty_gr=circshift(atomtype_layer1or.*mmytmp(:,:,1),[0,-2,0])+...
            circshift(atomtype_layer1or.*mmytmp(:,:,1),[1,0,0])+...
            circshift(atomtype_layer1or.*mmytmp(:,:,1),[-1,0,0]);
        shift_matz_gr=circshift(atomtype_layer1or.*mmztmp(:,:,1),[0,-2,0])+...
            circshift(atomtype_layer1or.*mmztmp(:,:,1),[1,0,0])+...
            circshift(atomtype_layer1or.*mmztmp(:,:,1),[-1,0,0]);
        %[0,-2,0], shift left 2
        %[1,0,0], shift down 1

        %J2 experienced by orange atoms
        shift_matx_or=circshift(atomtype_layer1gr.*mmxtmp(:,:,1),[0,2,0])+...
            circshift(atomtype_layer1gr.*mmxtmp(:,:,1),[1,0,0])+...
            circshift(atomtype_layer1gr.*mmxtmp(:,:,1),[-1,0,0]);
        shift_maty_or=circshift(atomtype_layer1gr.*mmytmp(:,:,1),[0,2,0])+...
            circshift(atomtype_layer1gr.*mmytmp(:,:,1),[1,0,0])+...
            circshift(atomtype_layer1gr.*mmytmp(:,:,1),[-1,0,0]);
        shift_matz_or=circshift(atomtype_layer1gr.*mmztmp(:,:,1),[0,2,0])+...
            circshift(atomtype_layer1gr.*mmztmp(:,:,1),[1,0,0])+...
            circshift(atomtype_layer1gr.*mmztmp(:,:,1),[-1,0,0]);

        mmxtmpJ2(:,:,1)=shift_matx_gr+shift_matx_or;
        mmytmpJ2(:,:,1)=shift_maty_gr+shift_maty_or;
        mmztmpJ2(:,:,1)=shift_matz_gr+shift_matz_or;

        %% calculate J3
        shift_matx(:,:,1)=circshift(atomtype_layer2p.*mmxtmp(:,:,2),[0,1])+...
            circshift(atomtype_layer2p.*mmxtmp(:,:,2),[-1,-1])+...
            circshift(atomtype_layer2p.*mmxtmp(:,:,2),[1,-1]);
        shift_maty(:,:,1)=circshift(atomtype_layer2p.*mmytmp(:,:,2),[0,1])+...
            circshift(atomtype_layer2p.*mmytmp(:,:,2),[-1,-1])+...
            circshift(atomtype_layer2p.*mmytmp(:,:,2),[1,-1]);
        shift_matz(:,:,1)=circshift(atomtype_layer2p.*mmztmp(:,:,2),[0,1])+...
            circshift(atomtype_layer2p.*mmztmp(:,:,2),[-1,-1])+...
            circshift(atomtype_layer2p.*mmztmp(:,:,2),[1,-1]);
        %[0,1], shift right 1
        mmxtmpJ3(:,:,1)=shift_matx;
        mmytmpJ3(:,:,1)=shift_maty;
        mmztmpJ3(:,:,1)=shift_matz;

        %% calculate J4
        %J4 experienced by green atoms
        %blue in the 2nd layer is identical to orange in 1st layer
        shift_matx_gr=circshift(atomtype_layer1or.*mmxtmp(:,:,2),[0,-2])+...
            circshift(atomtype_layer1or.*mmxtmp(:,:,2),[-1,0])+...
            circshift(atomtype_layer1or.*mmxtmp(:,:,2),[1,0]);
        shift_maty_gr=circshift(atomtype_layer1or.*mmytmp(:,:,2),[0,-2])+...
            circshift(atomtype_layer1or.*mmytmp(:,:,2),[-1,0])+...
            circshift(atomtype_layer1or.*mmytmp(:,:,2),[1,0]);
        shift_matz_gr=circshift(atomtype_layer1or.*mmztmp(:,:,2),[0,-2])+...
            circshift(atomtype_layer1or.*mmztmp(:,:,2),[-1,0])+...
            circshift(atomtype_layer1or.*mmztmp(:,:,2),[1,0]);
        %J4 experienced by orange atoms
        shift_matx_or=circshift(atomtype_layer2p.*mmxtmp(:,:,2),[0,-1])+...
            circshift(atomtype_layer2p.*mmxtmp(:,:,2),[1,1])+...
            circshift(atomtype_layer2p.*mmxtmp(:,:,2),[-1,1]);
        shift_maty_or=circshift(atomtype_layer2p.*mmytmp(:,:,2),[0,-1])+...
            circshift(atomtype_layer2p.*mmytmp(:,:,2),[1,1])+...
            circshift(atomtype_layer2p.*mmytmp(:,:,2),[-1,1]);
        shift_matz_or=circshift(atomtype_layer2p.*mmztmp(:,:,2),[0,-1])+...
            circshift(atomtype_layer2p.*mmztmp(:,:,2),[1,1])+...
            circshift(atomtype_layer2p.*mmztmp(:,:,2),[-1,1]);

        mmxtmpJ4(:,:,1)=shift_matx_gr+shift_matx_or;
        mmytmpJ4(:,:,1)=shift_maty_gr+shift_maty_or;
        mmztmpJ4(:,:,1)=shift_matz_gr+shift_matz_or;

    elseif i==h
        %% calculate J1
        %no J1 for red atoms
        mmxtmpJ1(:,:,h)=atomtype_layer2p.*mmxtmp(:,:,h-1);
        mmytmpJ1(:,:,h)=atomtype_layer2p.*mmytmp(:,:,h-1);
        mmztmpJ1(:,:,h)=atomtype_layer2p.*mmztmp(:,:,h-1);

        %% calculate J2
        %J2 experienced by black atoms
        %green in the 1st layer is identical to red in 3rd(last) layer
        shift_matx_black=circshift(atomtype_layer1gr.*mmxtmp(:,:,h),[0,-1])+...
            circshift(atomtype_layer1gr.*mmxtmp(:,:,h),[1,1])+...
            circshift(atomtype_layer1gr.*mmxtmp(:,:,h),[-1,1]);
        shift_maty_black=circshift(atomtype_layer1gr.*mmytmp(:,:,h),[0,-1])+...
            circshift(atomtype_layer1gr.*mmytmp(:,:,h),[1,1])+...
            circshift(atomtype_layer1gr.*mmytmp(:,:,h),[-1,1]);
        shift_matz_black=circshift(atomtype_layer1gr.*mmztmp(:,:,h),[0,-1])+...
            circshift(atomtype_layer1gr.*mmztmp(:,:,h),[1,1])+...
            circshift(atomtype_layer1gr.*mmztmp(:,:,h),[-1,1]);

        %J2 experienced by red atoms
        %purple in the 2nd layer is identical to black in 3rd(last) layer
        shift_matx_red=circshift(atomtype_layer2p.*mmxtmp(:,:,h),[0,1])+...
            circshift(atomtype_layer2p.*mmxtmp(:,:,h),[1,-1])+...
            circshift(atomtype_layer2p.*mmxtmp(:,:,h),[-1,-1]);
        shift_maty_red=circshift(atomtype_layer2p.*mmytmp(:,:,h),[0,1])+...
            circshift(atomtype_layer2p.*mmytmp(:,:,h),[1,-1])+...
            circshift(atomtype_layer2p.*mmytmp(:,:,h),[-1,-1]);
        shift_matz_red=circshift(atomtype_layer2p.*mmztmp(:,:,h),[0,1])+...
            circshift(atomtype_layer2p.*mmztmp(:,:,h),[1,-1])+...
            circshift(atomtype_layer2p.*mmztmp(:,:,h),[-1,-1]);

        mmxtmpJ2(:,:,h)=shift_matx_black+shift_matx_red;
        mmytmpJ2(:,:,h)=shift_maty_black+shift_maty_red;
        mmztmpJ2(:,:,h)=shift_matz_black+shift_matz_red;

        %% calculate J3
        %no J3 for black atoms
        %blue in the 2nd layer is identical to orange in 1st layer
        shift_matx=circshift(atomtype_layer1or.*mmxtmp(:,:,h-1),[0,-2])+...
            circshift(atomtype_layer1or.*mmxtmp(:,:,h-1),[-1,0])+...
            circshift(atomtype_layer1or.*mmxtmp(:,:,h-1),[1,0]);
        shift_maty=circshift(atomtype_layer1or.*mmytmp(:,:,h-1),[0,-2])+...
            circshift(atomtype_layer1or.*mmytmp(:,:,h-1),[-1,0])+...
            circshift(atomtype_layer1or.*mmytmp(:,:,h-1),[1,0]);
        shift_matz=circshift(atomtype_layer1or.*mmztmp(:,:,h-1),[0,-2])+...
            circshift(atomtype_layer1or.*mmztmp(:,:,h-1),[-1,0])+...
            circshift(atomtype_layer1or.*mmztmp(:,:,h-1),[1,0]);

        mmxtmpJ3(:,:,h)=shift_matx;
        mmytmpJ3(:,:,h)=shift_maty;
        mmztmpJ3(:,:,h)=shift_matz;

        %% calculate J4
        %J4 experienced by black atoms
        %black atoms only have three J4
        %blue in the 2nd layer is identical to orange in 1st layer
        shift_matx_black=circshift(atomtype_layer1or.*mmxtmp(:,:,h-1),[0,1])+...
            circshift(atomtype_layer1or.*mmxtmp(:,:,h-1),[-1,-1])+...
            circshift(atomtype_layer1or.*mmxtmp(:,:,h-1),[1,-1]);
        shift_maty_black=circshift(atomtype_layer1or.*mmytmp(:,:,h-1),[0,1])+...
            circshift(atomtype_layer1or.*mmytmp(:,:,h-1),[-1,-1])+...
            circshift(atomtype_layer1or.*mmytmp(:,:,h-1),[1,-1]);
        shift_matz_black=circshift(atomtype_layer1or.*mmztmp(:,:,h-1),[0,1])+...
            circshift(atomtype_layer1or.*mmztmp(:,:,h-1),[-1,-1])+...
            circshift(atomtype_layer1or.*mmztmp(:,:,h-1),[1,-1]);
        %J4 experienced by red atoms
        %red atoms only have three J4
        %blue in the 2nd layer is identical to orange in 1st layer
        shift_matx_red=circshift(atomtype_layer2p.*mmxtmp(:,:,h-1),[0,1])+...
            circshift(atomtype_layer2p.*mmxtmp(:,:,h-1),[-1,-1])+...
            circshift(atomtype_layer2p.*mmxtmp(:,:,h-1),[1,-1]);
        shift_maty_red=circshift(atomtype_layer2p.*mmytmp(:,:,h-1),[0,1])+...
            circshift(atomtype_layer2p.*mmytmp(:,:,h-1),[-1,-1])+...
            circshift(atomtype_layer2p.*mmytmp(:,:,h-1),[1,-1]);
        shift_matz_red=circshift(atomtype_layer2p.*mmztmp(:,:,h-1),[0,1])+...
            circshift(atomtype_layer2p.*mmztmp(:,:,h-1),[-1,-1])+...
            circshift(atomtype_layer2p.*mmztmp(:,:,h-1),[1,-1]);

        mmxtmpJ4(:,:,h)=shift_matx_black+shift_matx_red;
        mmytmpJ4(:,:,h)=shift_maty_black+shift_maty_red;
        mmztmpJ4(:,:,h)=shift_matz_black+shift_matz_red;

    else
        %green atom, next layer
        tmpgr_add_x= atomtype_layer1gr.*mmxtmp(:,:,i+1);
        tmpgr_add_y= atomtype_layer1gr.*mmytmp(:,:,i+1);
        tmpgr_add_z= atomtype_layer1gr.*mmztmp(:,:,i+1);
        %green atom, prev layer
        tmpgr_min_x= atomtype_layer1gr.*mmxtmp(:,:,i-1);
        tmpgr_min_y= atomtype_layer1gr.*mmytmp(:,:,i-1);
        tmpgr_min_z= atomtype_layer1gr.*mmztmp(:,:,i-1);
        %green atom, the same layer
        tmpgr_x= atomtype_layer1gr.*mmxtmp(:,:,i);
        tmpgr_y= atomtype_layer1gr.*mmytmp(:,:,i);
        tmpgr_z= atomtype_layer1gr.*mmztmp(:,:,i);

        %orange atom, next layer
        tmpor_add_x= atomtype_layer1or.*mmxtmp(:,:,i+1);
        tmpor_add_y= atomtype_layer1or.*mmytmp(:,:,i+1);
        tmpor_add_z= atomtype_layer1or.*mmztmp(:,:,i+1);
        %orange atom, prev layer
        tmpor_min_x= atomtype_layer1or.*mmxtmp(:,:,i-1);
        tmpor_min_y= atomtype_layer1or.*mmytmp(:,:,i-1);
        tmpor_min_z= atomtype_layer1or.*mmztmp(:,:,i-1);
        %orange atom, the same layer
        tmpor_x= atomtype_layer1or.*mmxtmp(:,:,i);
        tmpor_y= atomtype_layer1or.*mmytmp(:,:,i);
        tmpor_z= atomtype_layer1or.*mmztmp(:,:,i);

        %purple atom, next layer
        tmpp_add_x= atomtype_layer2p.*mmxtmp(:,:,i+1);
        tmpp_add_y= atomtype_layer2p.*mmytmp(:,:,i+1);
        tmpp_add_z= atomtype_layer2p.*mmztmp(:,:,i+1);
        %purple atom, prev layer
        tmpp_min_x= atomtype_layer2p.*mmxtmp(:,:,i-1);
        tmpp_min_y= atomtype_layer2p.*mmytmp(:,:,i-1);
        tmpp_min_z= atomtype_layer2p.*mmztmp(:,:,i-1);
        %purple atom, the same layer
        tmpp_x= atomtype_layer2p.*mmxtmp(:,:,i);
        tmpp_y= atomtype_layer2p.*mmytmp(:,:,i);
        tmpp_z= atomtype_layer2p.*mmztmp(:,:,i);

        %blue in the 2nd layer is identical to orange in 1st layer

        %green in the 1st layer is identical to red in 3rd(last) layer
        %red in the 3nd layer is identical to green in 1st layer

        %purple in the 2nd layer is identical to black in 3rd(last) layer
        %black in the 3nd layer is identical to purple in 2nd layer
        switch mod(i-1,3)
            case 0
                %% calculate J1
                mmxtmpJ1(:,:,i)=tmpgr_add_x+tmpor_min_x;
                mmytmpJ1(:,:,i)=tmpgr_add_y+tmpor_min_y;
                mmztmpJ1(:,:,i)=tmpgr_add_z+tmpor_min_z;
                %% calculate J2
                %J2 experienced by green atoms
                shift_matx_gr=circshift(tmpor_x,[0,-2,0])+circshift(tmpor_x,[1,0,0])+...
                    circshift(tmpor_x,[-1,0,0]);
                shift_maty_gr=circshift(tmpor_y,[0,-2,0])+circshift(tmpor_y,[1,0,0])+...
                    circshift(tmpor_y,[-1,0,0]);
                shift_matz_gr=circshift(tmpor_z,[0,-2,0])+circshift(tmpor_z,[1,0,0])+...
                    circshift(tmpor_z,[-1,0,0]);
                %J2 experienced by orange atoms
                shift_matx_or=circshift(tmpgr_x,[0,2,0])+circshift(tmpgr_x,[1,0,0])+...
                    circshift(tmpgr_x,[-1,0,0]);
                shift_maty_or=circshift(tmpgr_y,[0,2,0])+circshift(tmpgr_y,[1,0,0])+...
                    circshift(tmpgr_y,[-1,0,0]);
                shift_matz_or=circshift(tmpgr_z,[0,2,0])+circshift(tmpgr_z,[1,0,0])+...
                    circshift(tmpgr_z,[-1,0,0]);

                mmxtmpJ2(:,:,i)=shift_matx_gr+shift_matx_or;
                mmytmpJ2(:,:,i)=shift_maty_gr+shift_maty_or;
                mmztmpJ2(:,:,i)=shift_matz_gr+shift_matz_or;

                %% calculate J3
                %J3 experienced by green atoms
                shift_matx_gr=circshift(tmpp_add_x,[0,1])+circshift(tmpp_add_x,[-1,-1])+...
                    circshift(tmpp_add_x,[1,-1]);
                shift_maty_gr=circshift(tmpp_add_y,[0,1])+circshift(tmpp_add_y,[-1,-1])+...
                    circshift(tmpp_add_y,[1,-1]);
                shift_matz_gr=circshift(tmpp_add_z,[0,1])+circshift(tmpp_add_z,[-1,-1])+...
                    circshift(tmpp_add_z,[1,-1]);
                %J3 experienced by orange atoms
                %black in the 3nd layer is identical to purple in 2nd layer
                shift_matx_or=circshift(tmpp_min_x,[0,-1])+circshift(tmpp_min_x,[-1,1])+...
                    circshift(tmpp_min_x,[1,1]);
                shift_maty_or=circshift(tmpp_min_y,[0,-1])+circshift(tmpp_min_y,[-1,1])+...
                    circshift(tmpp_min_y,[1,1]);
                shift_matz_or=circshift(tmpp_min_z,[0,-1])+circshift(tmpp_min_z,[-1,1])+...
                    circshift(tmpp_min_z,[1,1]);

                mmxtmpJ3(:,:,i)=shift_matx_gr+shift_matx_or;
                mmytmpJ3(:,:,i)=shift_maty_gr+shift_maty_or;
                mmztmpJ3(:,:,i)=shift_matz_gr+shift_matz_or;

                %% calculate J4
                %J4 experienced by green atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                %black in the 3nd layer is identical to purple in 2nd layer
                shift_matx_gr=circshift(tmpor_add_x,[0,-2])+...
                    circshift(tmpor_add_x,[-1,0])+...
                    circshift(tmpor_add_x,[1,0])+...
                    circshift(tmpp_min_x,[0,1])+...
                    circshift(tmpp_min_x,[-1,-1])+...
                    circshift(tmpp_min_x,[1,-1]);
                shift_maty_gr=circshift(tmpor_add_y,[0,-2])+...
                    circshift(tmpor_add_y,[-1,0])+...
                    circshift(tmpor_add_y,[1,0])+...
                    circshift(tmpp_min_y,[0,1])+...
                    circshift(tmpp_min_y,[-1,-1])+...
                    circshift(tmpp_min_y,[1,-1]);
                shift_matz_gr=circshift(tmpor_add_z,[0,-2])+...
                    circshift(tmpor_add_z,[-1,0])+...
                    circshift(tmpor_add_z,[1,0])+...
                    circshift(tmpp_min_z,[0,1])+...
                    circshift(tmpp_min_z,[-1,-1])+...
                    circshift(tmpp_min_z,[1,-1]);
                %J4 experienced by orange atoms
                %red in the 3nd layer is identical to green in 1st layer
                shift_matx_or=circshift(tmpp_add_x,[0,-1])+...
                    circshift(tmpp_add_x,[1,1])+...
                    circshift(tmpp_add_x,[-1,1])+...
                    circshift(tmpgr_min_x,[0,2])+...
                    circshift(tmpgr_min_x,[1,0])+...
                    circshift(tmpgr_min_x,[-1,0]);
                shift_maty_or=circshift(tmpp_add_y,[0,-1])+...
                    circshift(tmpp_add_y,[1,1])+...
                    circshift(tmpp_add_y,[-1,1])+...
                    circshift(tmpgr_min_y,[0,2])+...
                    circshift(tmpgr_min_y,[1,0])+...
                    circshift(tmpgr_min_y,[-1,0]);
                shift_matz_or=circshift(tmpp_add_z,[0,-1])+...
                    circshift(tmpp_add_z,[1,1])+...
                    circshift(tmpp_add_z,[-1,1])+...
                    circshift(tmpgr_min_z,[0,2])+...
                    circshift(tmpgr_min_z,[1,0])+...
                    circshift(tmpgr_min_z,[-1,0]);

                mmxtmpJ4(:,:,i)=shift_matx_gr+shift_matx_or;
                mmytmpJ4(:,:,i)=shift_maty_gr+shift_maty_or;
                mmztmpJ4(:,:,i)=shift_matz_gr+shift_matz_or;

            case 1
                %% calculate J1
                mmxtmpJ1(:,:,i)=tmpp_add_x+tmpor_min_x;
                mmytmpJ1(:,:,i)=tmpp_add_y+tmpor_min_y;
                mmztmpJ1(:,:,i)=tmpp_add_z+tmpor_min_z;

                %% calculate J2
                %J2 experienced by blue atoms
                shift_matx_blue=circshift(tmpp_x,[0,-1,0])+circshift(tmpp_x,[1,1,0])+...
                    circshift(tmpp_x,[-1,1,0]);
                shift_maty_blue=circshift(tmpp_y,[0,-1,0])+circshift(tmpp_y,[1,1,0])+...
                    circshift(tmpp_y,[-1,1,0]);
                shift_matz_blue=circshift(tmpp_z,[0,-1,0])+circshift(tmpp_z,[1,1,0])+...
                    circshift(tmpp_z,[-1,1,0]);

                %J2 experienced by purple atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                shift_matx_purple=circshift(tmpor_x,[0,1,0])+circshift(tmpor_x,[1,-1,0])+...
                    circshift(tmpor_x,[-1,-1,0]);
                shift_maty_purple=circshift(tmpor_y,[0,1,0])+circshift(tmpor_y,[1,-1,0])+...
                    circshift(tmpor_y,[-1,-1,0]);
                shift_matz_purple=circshift(tmpor_z,[0,1,0])+circshift(tmpor_z,[1,-1,0])+...
                    circshift(tmpor_z,[-1,-1,0]);

                mmxtmpJ2(:,:,i)=shift_matx_blue+shift_matx_purple;
                mmytmpJ2(:,:,i)=shift_maty_blue+shift_maty_purple;
                mmztmpJ2(:,:,i)=shift_matz_blue+shift_matz_purple;

                %% calculate J3
                %J3 experienced by blue atoms
                %red in the 3rd layer is identical to green in 1st layer
                shift_matx_blue=circshift(tmpgr_add_x,[0,2])+circshift(tmpgr_add_x,[-1,0])...
                    +circshift(tmpgr_add_x,[1,0]);
                shift_maty_blue=circshift(tmpgr_add_y,[0,2])+circshift(tmpgr_add_y,[-1,0])...
                    +circshift(tmpgr_add_y,[1,0]);
                shift_matz_blue=circshift(tmpgr_add_z,[0,2])+circshift(tmpgr_add_z,[-1,0])...
                    +circshift(tmpgr_add_z,[1,0]);
                %J3 experienced by purple atoms
                shift_matx_purple=circshift(tmpgr_min_x,[0,-1])+circshift(tmpgr_min_x,[-1,1])...
                    +circshift(tmpgr_min_x,[1,1]);
                shift_maty_purple=circshift(tmpgr_min_y,[0,-1])+circshift(tmpgr_min_y,[-1,1])...
                    +circshift(tmpgr_min_y,[1,1]);
                shift_matz_purple=circshift(tmpgr_min_z,[0,-1])+circshift(tmpgr_min_z,[-1,1])...
                    +circshift(tmpgr_min_z,[1,1]);

                mmxtmpJ3(:,:,i)=shift_matx_blue+shift_matx_purple;
                mmytmpJ3(:,:,i)=shift_maty_blue+shift_maty_purple;
                mmztmpJ3(:,:,i)=shift_matz_blue+shift_matz_purple;

                %% calculate J4
                %J4 experienced by blue atoms
                %black in the 3nd layer is identical to purple in 2nd layer
                shift_matx_black=circshift(tmpp_add_x,[0,-1])+...
                    circshift(tmpp_add_x,[-1,1])+...
                    circshift(tmpp_add_x,[1,1])+...
                    circshift(tmpgr_min_x,[0,2])+...
                    circshift(tmpgr_min_x,[-1,0])+...
                    circshift(tmpgr_min_x,[1,0]);
                shift_maty_black=circshift(tmpp_add_y,[0,-1])+...
                    circshift(tmpp_add_y,[-1,1])+...
                    circshift(tmpp_add_y,[1,1])+...
                    circshift(tmpgr_min_y,[0,2])+...
                    circshift(tmpgr_min_y,[-1,0])+...
                    circshift(tmpgr_min_y,[1,0]);
                shift_matz_black=circshift(tmpp_add_z,[0,-1])+...
                    circshift(tmpp_add_z,[-1,1])+...
                    circshift(tmpp_add_z,[1,1])+...
                    circshift(tmpgr_min_z,[0,2])+...
                    circshift(tmpgr_min_z,[-1,0])+...
                    circshift(tmpgr_min_z,[1,0]);
                %J4 experienced by purple atoms
                %red in the 3nd layer is identical to green in 1st layer
                shift_matx_purple=circshift(tmpgr_add_x,[0,-1])+...
                    circshift(tmpgr_add_x,[-1,1])+...
                    circshift(tmpgr_add_x,[1,1])+...
                    circshift(tmpor_min_x,[0,1])+...
                    circshift(tmpor_min_x,[-1,-1])+...
                    circshift(tmpor_min_x,[1,-1]);
                shift_maty_purple=circshift(tmpgr_add_y,[0,-1])+...
                    circshift(tmpgr_add_y,[-1,1])+...
                    circshift(tmpgr_add_y,[1,1])+...
                    circshift(tmpor_min_y,[0,1])+...
                    circshift(tmpor_min_y,[-1,-1])+...
                    circshift(tmpor_min_y,[1,-1]);
                shift_matz_purple=circshift(tmpgr_add_z,[0,-1])+...
                    circshift(tmpgr_add_z,[-1,1])+...
                    circshift(tmpgr_add_z,[1,1])+...
                    circshift(tmpor_min_z,[0,1])+...
                    circshift(tmpor_min_z,[-1,-1])+...
                    circshift(tmpor_min_z,[1,-1]);

                mmxtmpJ4(:,:,i)=shift_matx_black+shift_matx_purple;
                mmytmpJ4(:,:,i)=shift_maty_black+shift_maty_purple;
                mmztmpJ4(:,:,i)=shift_matz_black+shift_matz_purple;

            case 2
                %% calculate J1
                mmxtmpJ1(:,:,i)=tmpgr_add_x+tmpp_min_x;
                mmytmpJ1(:,:,i)=tmpgr_add_y+tmpp_min_y;
                mmztmpJ1(:,:,i)=tmpgr_add_z+tmpp_min_z;

                %% calculate J2
                %J2 experienced by black atoms
                %green in the 1st layer is identical to red in 3rd(last) layer
                shift_matx_black=circshift(tmpgr_x,[0,-1])+circshift(tmpgr_x,[1,1])+...
                    circshift(tmpgr_x,[-1,1]);
                shift_maty_black=circshift(tmpgr_y,[0,-1])+circshift(tmpgr_y,[1,1])+...
                    circshift(tmpgr_y,[-1,1]);
                shift_matz_black=circshift(tmpgr_z,[0,-1])+circshift(tmpgr_z,[1,1])+...
                    circshift(tmpgr_z,[-1,1]);
                %J2 experienced by red atoms
                %purple in the 2nd layer is identical to black in 3rd(last) layer
                shift_matx_red=circshift(tmpp_x,[0,1])+circshift(tmpp_x,[1,-1])+...
                    circshift(tmpp_x,[-1,-1]);
                shift_maty_red=circshift(tmpp_y,[0,1])+circshift(tmpp_y,[1,-1])+...
                    circshift(tmpp_y,[-1,-1]);
                shift_matz_red=circshift(tmpp_z,[0,1])+circshift(tmpp_z,[1,-1])+...
                    circshift(tmpp_z,[-1,-1]);

                mmxtmpJ2(:,:,i)=shift_matx_black+shift_matx_red;
                mmytmpJ2(:,:,i)=shift_maty_black+shift_maty_red;
                mmztmpJ2(:,:,i)=shift_matz_black+shift_matz_red;

                %% calculate J3
                %J3 for red atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                shift_matx_red=circshift(tmpor_min_x,[0,-2])+circshift(tmpor_min_x,[-1,0])+...
                    circshift(tmpor_min_x,[1,0]);
                shift_maty_red=circshift(tmpor_min_y,[0,-2])+circshift(tmpor_min_y,[-1,0])+...
                    circshift(tmpor_min_y,[1,0]);
                shift_matz_red=circshift(tmpor_min_z,[0,-2])+circshift(tmpor_min_z,[-1,0])+...
                    circshift(tmpor_min_z,[1,0]);
                %J3 for black atoms
                shift_matx_black=circshift(tmpor_add_x,[0,1])+circshift(tmpor_add_x,[-1,-1])+...
                    circshift(tmpor_add_x,[1,-1]);
                shift_maty_black=circshift(tmpor_add_y,[0,1])+circshift(tmpor_add_y,[-1,-1])+...
                    circshift(tmpor_add_y,[1,-1]);
                shift_matz_black=circshift(tmpor_add_z,[0,1])+circshift(tmpor_add_z,[-1,-1])+...
                    circshift(tmpor_add_z,[1,-1]);

                mmxtmpJ3(:,:,i)=shift_matx_red+shift_matx_black;
                mmytmpJ3(:,:,i)=shift_maty_red+shift_maty_black;
                mmztmpJ3(:,:,i)=shift_matz_red+shift_matz_black;

                %% calculate J4
                %J4 experienced by black atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                shift_matx_black=circshift(tmpgr_add_x,[0,-1])+...
                    circshift(tmpgr_add_x,[-1,1])+...
                    circshift(tmpgr_add_x,[1,1])+...
                    circshift(tmpor_min_x,[0,1])+...
                    circshift(tmpor_min_x,[-1,-1])+...
                    circshift(tmpor_min_x,[1,-1]);
                shift_maty_black=circshift(tmpgr_add_y,[0,-1])+...
                    circshift(tmpgr_add_y,[-1,1])+...
                    circshift(tmpgr_add_y,[1,1])+...
                    circshift(tmpor_min_y,[0,1])+...
                    circshift(tmpor_min_y,[-1,-1])+...
                    circshift(tmpor_min_y,[1,-1]);
                shift_matz_black=circshift(tmpgr_add_z,[0,-1])+...
                    circshift(tmpgr_add_z,[-1,1])+...
                    circshift(tmpgr_add_z,[1,1])+...
                    circshift(tmpor_min_z,[0,1])+...
                    circshift(tmpor_min_z,[-1,-1])+...
                    circshift(tmpor_min_z,[1,-1]);
                %J4 experienced by red atoms
                %blue in the 2nd layer is identical to orange in 1st layer
                shift_matx_red=circshift(tmpor_add_x,[1,0])+...
                    circshift(tmpor_add_x,[-1,0])+...
                    circshift(tmpor_add_x,[0,-2])+...
                    circshift(tmpp_min_x,[0,1])+...
                    circshift(tmpp_min_x,[-1,-1])+...
                    circshift(tmpp_min_x,[1,-1]);
                shift_maty_red=circshift(tmpor_add_y,[1,0])+...
                    circshift(tmpor_add_y,[-1,0])+...
                    circshift(tmpor_add_y,[0,-2])+...
                    circshift(tmpp_min_y,[0,1])+...
                    circshift(tmpp_min_y,[-1,-1])+...
                    circshift(tmpp_min_y,[1,-1]);
                shift_matz_red=circshift(tmpor_add_z,[1,0])+...
                    circshift(tmpor_add_z,[-1,0])+...
                    circshift(tmpor_add_z,[0,-2])+...
                    circshift(tmpp_min_z,[0,1])+...
                    circshift(tmpp_min_z,[-1,-1])+...
                    circshift(tmpp_min_z,[1,-1]);

                mmxtmpJ4(:,:,i)=shift_matx_black+shift_matx_red;
                mmytmpJ4(:,:,i)=shift_maty_black+shift_maty_red;
                mmztmpJ4(:,:,i)=shift_matz_black+shift_matz_red;
            otherwise
                error('unexpected index');
        end
    end
    mmxtmpJ_1(:,:,i)=mmxtmpJ1(:,:,i);mmytmpJ_1(:,:,i)=mmytmpJ1(:,:,i);mmztmpJ_1(:,:,i)=mmztmpJ1(:,:,i);mmxtmpJ_2(:,:,i)=mmxtmpJ2(:,:,i);mmytmpJ_2(:,:,i)=mmytmpJ2(:,:,i);mmztmpJ_2(:,:,i)=mmztmpJ2(:,:,i);
    mmxtmpJ_3(:,:,i)=mmxtmpJ3(:,:,i);mmytmpJ_3(:,:,i)=mmytmpJ3(:,:,i);mmztmpJ_3(:,:,i)=mmztmpJ3(:,:,i);mmxtmpJ_4(:,:,i)=mmxtmpJ4(:,:,i);mmytmpJ_4(:,:,i)=mmytmpJ4(:,:,i);mmztmpJ_4(:,:,i)=mmztmpJ4(:,:,i);
end
load('debugtmp.mat');
isequal(mmxtmpJzx_1, mmxtmpJ_1)&isequal(mmytmpJzx_1, mmytmpJ_1)&isequal(mmztmpJzx_1, mmztmpJ_1)&...
    isequal(mmxtmpJzx_2, mmxtmpJ_2)&isequal(mmytmpJzx_2, mmytmpJ_2)&isequal(mmztmpJzx_2, mmztmpJ_2)&...
    isequal(mmxtmpJzx_3, mmxtmpJ_3)&isequal(mmytmpJzx_3, mmytmpJ_3)&isequal(mmztmpJzx_3, mmztmpJ_3)&...
    isequal(mmxtmpJzx_4, mmxtmpJ_4)&isequal(mmytmpJzx_4, mmytmpJ_4)&isequal(mmztmpJzx_4, mmztmpJ_4)
